apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: basic-model
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          labels:
            applicationId: "basic-model"
            queue: root.system.system-normal
          annotations:
            yunikorn.apache.org/schedulingPolicyParameters: "gangSchedulingStyle=Hard"
            yunikorn.apache.org/task-group-name: basic-model
            yunikorn.apache.org/task-groups: |-
              [{
                  "name": "basic-model",
                  "minMember": 2,
                  "minResource": {
                    "cpu": "30m",
                    "memory": "60M",
                    "nvidia.com/gpu": 2
                  },
                  "nodeSelector": {},
                  "tolerations": [],
                  "affinity": {}
              }]
        spec:
          schedulerName: yunikorn
          activeDeadlineSeconds: 300
          containers:
            - args:
                - "--num_gpus"
                - "0"
                - "--epochs"
                - "2"
                - "--gpu_memory_limit"
                - "1024"
              name: tensorflow
              image: kubeflow/tf-mnist-test:1.0
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  nvidia.com/gpu: 1